# ┌─────────────────────────────────────────────────────────────────────────────────────────+
# │ [ ArcCheck 콘피그 파일입니다. ]
# │ [ 불필요한 메시지는 지우거나 해당 라인 앞에 '#'을 붇여서 주석 처리해주세요. ]
# │
# │ - ARCADIA 디스코드 : https://discord.gg/NanAFkRdww
# │ - ARCADIA 웹사이트 : https://arcadia.imweb.me/
# └─────────────────────────────────────────────────────────────────────────────────────────+

# ┌─────────────────────────────────────────────────────────────────────────────────────────+
# │
# │ [💸][ 수표 설정 ]
# │
# └─────────────────────────────────────────────────────────────────────────────────────────+
# {check_amount} : 수표 가격
check-item:
  type: PAPER
  name: "&6&l[ 수표 ] &f{check_amount}"
  custom_model_data: 123
  lore:
    "&6&l│ &7우클릭하여 사용가능합니다."

# ┌────────────────────────────────────────────────────────────────────────────────────────+
# │
# │ [🔊][ 사운드 설정 ]
# │
# └─────────────────────────────────────────────────────────────────────────────────────────+
sound:
  # 수표를 발급했을 때
  get_check: ENTITY_EXPERIENCE_ORB_PICKUP
  
  # 수표를 지급했을 때
  give_check: ENTITY_EXPERIENCE_ORB_PICKUP
  
  # 수표 발급을 실패했을 때
  failed_get_check: BLOCK_STONE_STEP

  # 수표를 클릭했을 때
  click_check: ENTITY_PLAYER_LEVELUP

# ┌─────────────────────────────────────────────────────────────────────────────────────────+
# │
# │ [💬][ 메시지 설정 ]
# │
# └─────────────────────────────────────────────────────────────────────────────────────────+
message:
  normal:
    # 접두사
    prefix: "&e&l[ 수표 ] &r"

    # config를 리로드 했을 때 출력됨
    reload_config: "&a콘피그를 리로드했습니다."

  error:
    # 콘솔로 명령어를 입력했을 때 출력됨
    player_only: "&c플레이어만 입력이 가능한 커맨드입니다."

    # 권한이 없을 때 출력됨
    no_permission: "&c명령어를 사용할 권한이 없습니다."

    # 잘못된 명령어를 입력했을 때 출력됨
    wrong_command: "&c잘못된 명령어입니다."

    # 플레이어가 잘못된 명령어를 입력했을 때 출력됨
    player_wrong_command: "&r올바른 사용법: /수표 발행 <금액>"

  main:
    # 잔액이 부족할 때 출력됨
    not_enough_balance: "&f잔액이 부족합니다."

    # 수표를 발행했을 때 출력됨
    # {check_amount} : 수표 가격
    get_check: "&f{check_amount} 수표를 발행했습니다."

    # 수표를 사용했을 때 출력됨
    # {check_amount} : 수표 가격
    used_check: "&f{check_amount} 수표를 사용했습니다."
    
    # 수표를 지급할 때 출력됨
    # {check_amount} : 수표 가격
    # {player} : 플레이어 이름
    give_check: "&f{player}님에게 {check_amount} 수표를 지급했습니다."